### ISSUE TITLE
Unable to get error responses from the Psr18Client (symfony)

### ISSUE THREAD

**Issue by phartshorn** [go1com/rest#104]
There is a bug in version 4.3.1 and below of symfony\HttpClient, specifically the Psr18Client where the request call throws an exception without providing the response body. 4.3.2 and above apparently address this with the inclusion of the false parameter to the getContents call and the getHeaders call within the Psr18Client::sendRequest function.

Note that in version 4.3.1 and below, the getHeaders call does not recognise the false parameter and continues to throw the exception.

**Comment by and1truong** [comment]
@phartshorn is this still issue? May you provide some sample code?

Thanks

**Comment by phartshorn** [comment]
Since the rest component has been updated to Symfony ^4.3.2 the issue has been resolved. Thanks.

Closing ticket.
